### ISSUE TITLE
Computing multiple graphs by resampling does not work

### ISSUE THREAD

**Issue by auranic** [j-bac/ElPiGraph.Python#9]
import elpigraph
import numpy as np
data = np.random.random((1000,3)) 
PGs = elpigraph.computeElasticPrincipalTree(data, NumNodes=20,nReps=10,ProbPoint=0.9)

gives error message

/usr/local/lib/python3.7/dist-packages/elpigraph/_topologies.py:1090: RuntimeWarning: Mean of empty slice.
  mv = X.mean(axis=0)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-224a5192f185> in <module>()
      2 import numpy as np
      3 data = np.random.random((1000,3))
----> 4 PGs = elpigraph.computeElasticPrincipalTree(data, NumNodes=20,nReps=10,ProbPoint=0.9)

5 frames
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    584                              " minimum of %d is required%s."
    585                              % (n_samples, array.shape, ensure_min_samples,
--> 586                                 context))
    587 
    588     if ensure_min_features > 0 and array.ndim == 2:

ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required.

**Comment by j-bac** [comment]
solved
